// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SharedSecretsSchema = z.object({
  id: z.string().uuid(),
  algorithm: z.string().default('aes-256-gcm'),
  keyEncoding: z.string().default('utf8'),
  cipherText: z.string(),
  tag: z.string(),
  iv: z.string(),
  userId: z.string().uuid(),
  expiration: z.date()
});

export type TSharedSecrets = z.infer<typeof SharedSecretsSchema>;
export type TSharedSecretsInsert = Omit<z.input<typeof SharedSecretsSchema>, TImmutableDBKeys>;
export type TSharedSecretsUpdate = Partial<Omit<z.input<typeof SharedSecretsSchema>, TImmutableDBKeys>>;
